# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
        migrations.AddField(
            model_name='person',
            name='chequing_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='savings_amount',
            field=models.IntegerField(default=0),
        ),
    ]
